apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webserver.fullname" . }}-nginx-config
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
data:
  nginx.conf: |
    # Dynamic modules configuration
    load_module "/usr/lib64/nginx/modules/ngx_http_geoip2_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_http_cache_purge_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_http_headers_more_filter_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_http_sorted_querystring_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_mail_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_rtmp_module.so";
    load_module "/usr/lib64/nginx/modules/ngx_http_gridfs_module.so";

    worker_processes auto;
    worker_rlimit_nofile 50000;

    pid /opt/oro-nginx/var/run/nginx.pid;

    events {
      multi_accept on;
      worker_connections 30000;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;
      
      log_format extended '$http_x_real_ip - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time [$upstream_http_x_oro_info]';
      
      access_log /dev/stdout extended buffer=32k flush=5s;
      error_log /dev/stdout error;

      sendfile on;
      server_tokens off;

      types_hash_max_size           2048;
      types_hash_bucket_size        512;
      server_names_hash_bucket_size 256;
      server_names_hash_max_size    4096;
      variables_hash_max_size       4096;
      variables_hash_bucket_size    4096;

      keepalive_timeout   650s;
      keepalive_requests  10000;
      client_body_timeout 300s;
      send_timeout        30s;
      lingering_timeout   5s;
      tcp_nodelay         on;

      gzip              on;
      gzip_buffers      16 8k;
      gzip_comp_level   5;
      gzip_disable      msie6;
      gzip_min_length   1000;
      gzip_http_version 1.0;
      gzip_proxied      any;
      gzip_types        font/woff2 font/woff font/ttf text/plain application/javascript application/x-javascript text/javascript text/xml text/css image/svg+xml application/json;
      gzip_vary         on;

      client_body_temp_path   /opt/oro-nginx/var/client_body_temp;
      client_max_body_size    512m;
      client_body_buffer_size 1m;
      proxy_redirect          off;
      proxy_temp_path         /opt/oro-nginx/var/proxy_temp;
      proxy_connect_timeout   10s;
      proxy_send_timeout      180s;
      proxy_read_timeout      180s;
      proxy_buffers           32 4k;
      proxy_buffer_size       8k;
      proxy_http_version      1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Proxy "";
      proxy_headers_hash_bucket_size 64;

      fastcgi_buffer_size          128k;
      fastcgi_buffers              4 256k;
      fastcgi_busy_buffers_size    256k;
      fastcgi_connect_timeout      10s;
      fastcgi_ignore_client_abort  off;
      fastcgi_index                index.php;
      fastcgi_intercept_errors     on;
      fastcgi_read_timeout         600s;
      fastcgi_send_timeout         600s;
      fastcgi_temp_file_write_size 256k;
      fastcgi_temp_path            /opt/oro-nginx/var/fastcgi_temp;
      uwsgi_temp_path              /opt/oro-nginx/var/uwsgi_temp;
      scgi_temp_path               /opt/oro-nginx/var/scgi_temp;

      real_ip_header    X-Forwarded-For;
      real_ip_recursive on;
      set_real_ip_from  0.0.0.0/0;

      map_hash_bucket_size       2048;
      map_hash_max_size          262144;
      reset_timedout_connection  on;
      tcp_nopush                 on;

      # GeoIP2 module configuration
      geoip2 /usr/share/GeoIP2/GeoLite2-City.mmdb {
        auto_reload 30m;
        $geoip2_metadata_city_build metadata build_epoch;
        $geoip2_data_city_name default=London city names en;
        $geoip2_subdivisions_iso_code default=LND subdivisions 0 iso_code;
      }
      geoip2 /usr/share/GeoIP2/GeoLite2-Country.mmdb {
        auto_reload 30m;
        $geoip2_metadata_country_build metadata build_epoch;
        $geoip2_data_country_code default=US source=$remote_addr country iso_code;
        $geoip2_data_country_name country names en;
      }

      # Rate limiting zones
      limit_req_zone $binary_remote_addr zone=ip:10m rate=10r/s;
      limit_req_zone $uri zone=uri:10m rate=10r/s;
      limit_req_zone $binary_remote_addr zone=ws:10m rate=10r/s;
      limit_req_zone $binary_remote_addr zone=deny:10m rate=1r/s;

      # Rate limiting maps
      map $uri $limit_whitelist_uri {
        default 1;
        ~^/status 0;
        ~^/robots\.txt 0;
        ~^/favicon\.ico 0;
        ~^/media/ 0;
        ~^/bundles/ 0;
        ~^/build/ 0;
      }

      include "conf.d/*.conf";
      include "sites.d/*.conf";
      include "sites-enabled/*";
    }

  domain_com.conf: |
    server {
      listen      *:80;
      server_name _;
      resolver 10.21.0.10 valid=5s;
      add_header "set_real_ip_from" "0.0.0.0/0";
      add_header "real_ip_header" "X-Real-IP";
      add_header "real_ip_recursive" "on";
      try_files $uri @rewrite;

      root /var/www/oro/public;

      index index.php;
      access_log /dev/stdout extended buffer=32k flush=5s;
      error_log  /dev/stdout error;

      error_page 501 /501.html;
      error_page 502 /502.html;
      error_page 503 /503.html;
      error_page 401 /401.html;
      error_page 451 /451.html;

      location /501.html {
        internal;
        try_files /error_pages/501.$host.html /error_pages/501.html @fallback_501;
        root /mnt/persistent_shared;
      }

      location @fallback_501 {
        root /var/www/html;
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        add_header "Cache-Control" "no-cache";
      }

      location /502.html {
        internal;
        try_files /error_pages/502.$host.html /error_pages/502.html @fallback_502;
        root /mnt/persistent_shared;
      }

      location @fallback_502 {
        root /var/www/html;
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        add_header "Cache-Control" "no-cache";
      }

      location /503.html {
        internal;
        try_files /error_pages/503.$host.html /error_pages/503.html @fallback_503;
        root /mnt/persistent_shared;
      }

      location @fallback_503 {
        root /var/www/html;
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        add_header "Cache-Control" "no-cache";
      }

      location /401.html {
        internal;
        try_files /error_pages/401.$host.html /error_pages/401.html @fallback_401;
        root /mnt/persistent_shared;
      }

      location @fallback_401 {
        root /var/www/html;
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        add_header "Cache-Control" "no-cache";
      }

      location /451.html {
        internal;
        try_files /error_pages/451.$host.html /error_pages/451.html @fallback_451;
        root /mnt/persistent_shared;
      }

      location @fallback_451 {
        root /var/www/html;
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        add_header "Cache-Control" "no-cache";
      }

      location /status {
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        deny all;
        stub_status on;
        access_log off;
      }

      location =/OroCommerce.png {
        root /var/www/html;
      }

      location =/robots.txt {
        try_files /media/sitemaps/robots.$host.txt @robots;
        access_log off;
        log_not_found off;
        more_clear_headers Server;
        more_clear_headers X-Page-Speed;
        more_clear_headers X-Powered-By;
        more_clear_headers X-CF-Powered-By;
        add_header Cache-Control no-cache;
      }

      location @robots {
        rewrite ^ /media/sitemaps/robots.$host.txt;
        access_log off;
        log_not_found off;
        more_clear_headers Server;
        more_clear_headers X-Page-Speed;
        more_clear_headers X-Powered-By;
        more_clear_headers X-CF-Powered-By;
        add_header Cache-Control no-cache;
      }

      location @rewrite {
        if (-f /mnt/persistent_shared/maintenance_lock) { add_header "Cache-Control" "no-cache"; return 503; }
        rewrite ^/(.*)$ /index.php/$1;
      }

      location ~ /tracking\.php(/|$) {
        limit_req zone=ip burst=7 delay=5;
        limit_req zone=uri burst=17 delay=3;
        if (!-f $realpath_root$fastcgi_script_name) { return 404; }
        include fastcgi.conf;
        fastcgi_pass php-fpm-app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param GEOIP2_COUNTRY_CODE $geoip2_data_country_code;
        fastcgi_param GEOIP2_SUBDIVISION_ISO_CODE $geoip2_subdivisions_iso_code;
        fastcgi_param HTTPS on;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PHP_PATH /usr/bin/php;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        break;
      }

      location ~ /index\.php(/|$) {
        internal;
        limit_req zone=ip burst=7 delay=5;
        limit_req zone=uri burst=17 delay=3;
        if (!-f $realpath_root$fastcgi_script_name) { return 404; }
        include fastcgi.conf;
        fastcgi_pass php-fpm-app:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param GEOIP2_COUNTRY_CODE $geoip2_data_country_code;
        fastcgi_param GEOIP2_SUBDIVISION_ISO_CODE $geoip2_subdivisions_iso_code;
        fastcgi_param HTTPS on;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PHP_PATH /usr/bin/php;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        break;
      }

      location =/ws {
        limit_req zone=ws burst=10 delay=2;
        reset_timedout_connection on;
        proxy_pass http://ws:8080/;
        proxy_read_timeout 86400s;
        proxy_connect_timeout 180s;
        proxy_send_timeout 180s;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        proxy_buffer_size 64k;
        proxy_buffers 8 32k;
      }

      location ~* \.(?:jpg|jpeg|gif|png|ico|tiff|woff|woff2|eot|ttf|svg|svgz|mp4|ogg|ogv|webm|swf|flv|pdf|ppt|txt|bmp|rtf|webp|css|js|json)$ {
        set $limit_whitelist 0;
        if ( -f $request_filename ) { expires 30d; add_header "Cache-Control" "public"; }
        try_files $uri @rewrite;
        access_log off;
        log_not_found off;
        more_clear_headers Server;
        more_clear_headers X-Page-Speed;
        more_clear_headers X-Powered-By;
        more_clear_headers X-CF-Powered-By;
      }

      location ^~ /media/ {
        expires 3w;
        add_header "Cache-Control" "public";
        if ( $request_filename ~ robots(\..+)?\.txt$ ) { add_header "Cache-Control" "no-cache"; }
        if ( $request_filename ~ sitemaps(\/\.+)$ ) { add_header "Cache-Control" "no-cache"; }
        access_log off;
        log_not_found off;
        more_clear_headers Server X-Page-Speed X-Powered-By X-CF-Powered-By;
        recursive_error_pages on;
        error_page 404 = @rewrite;
      }

      location ~ /\.ht {
        deny all;
      }

      location ~ \.php$ {
        limit_req zone=deny burst=3;
        deny all;
      }

      if ($host ~* ^\*\.(.+)) {
          return 404;
      }
    } 