apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "database.name" . }}
