apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}-hl
  labels:
    app: {{ include "database.name" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "database.name" . }} 