apiVersion: v1
kind: Service
metadata:
  name: php-fpm-app
  labels:
    app: {{ include "phpfpm.name" . }}
    {{- include "phpfpm.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: php-fpm
  selector:
    app: {{ include "phpfpm.name" . }} 