apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [security]
    admin_user = {{ .Values.config.security.admin_user }}
    admin_password = {{ .Values.config.security.admin_password }}
    allow_embedding = {{ .Values.config.security.allow_embedding }}

    [server]
    http_port = {{ .Values.config.server.http_port }}
    domain = {{ .Values.config.server.domain }}
    root_url = {{ .Values.config.server.root_url }}
    serve_from_sub_path = {{ .Values.config.server.serve_from_sub_path }}

    [database]
    type = {{ .Values.config.database.type }}
    path = {{ .Values.config.database.path }}

    [session]
    provider = {{ .Values.config.session.provider }}
    provider_config = {{ .Values.config.session.provider_config }}

    [log]
    mode = {{ .Values.config.log.mode }}
    level = {{ .Values.config.log.level }}

    [users]
    allow_sign_up = false
    allow_org_create = false

    [auth.anonymous]
    enabled = false 