apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      containers:
        - name: grafana
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.config.security.admin_user }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.config.security.admin_password }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.http_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-files
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-config
          configMap:
            name: {{ include "grafana.fullname" . }}-config
        - name: grafana-datasources
          configMap:
            name: {{ include "grafana.fullname" . }}-datasources
        - name: grafana-dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        - name: grafana-dashboard-files
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        - name: grafana-storage
          {{- if .Values.deployment.volume.storageClass }}
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.deployment.volume.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana.fullname" . }}-storage
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.deployment.volume.storageClass }}
  storageClassName: {{ .Values.deployment.volume.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.deployment.volume.size }}
{{- end }} 