image:
  repository: oroinc/runtime
  tag: "6.1-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

websocket:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  volumes:
    oroApp:
      claimName: "oro-app-orocommerce-simple"
    cache:
      claimName: "cache-orocommerce-simple"
    maintenance:
      claimName: "maintenance-orocommerce-simple"
    publicStorage:
      claimName: "public-storage-orocommerce-simple"
    privateStorage:
      claimName: "private-storage-orocommerce-simple" 