{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orocommerce.fullname" . }}-default-deny
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS pour les dépendances externes
    - to: []
      ports:
        - protocol: TCP
          port: 443
---
{{- end }}
{{- if .Values.networkPolicies.allowInternal }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orocommerce.fullname" . }}-allow-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orocommerce.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from other OroCommerce pods
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "orocommerce.name" . }}
  egress:
    # Allow to other OroCommerce pods
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "orocommerce.name" . }}
    # Allow to PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow to Redis
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow to Elasticsearch
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: elasticsearch
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 9300
---
{{- end }}
{{- if .Values.networkPolicies.allowExternal }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orocommerce.fullname" . }}-allow-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "orocommerce.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow external traffic to frontend
    - from: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "orocommerce.fullname" . }}-allow-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orocommerce.name" . }}
  policyTypes:
    - Ingress
  ingress:
    # Allow Prometheus to scrape metrics
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: 9113  # nginx-exporter
        - protocol: TCP
          port: 9253  # php-fpm-exporter
---
{{- end }}
{{- end }} 