apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail.fullname" . }}
  labels:
    {{- include "mail.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mail.selectorLabels" . | nindent 4 }} 