{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail.fullname" . }}-ui
  labels:
    {{- include "mail.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "mail.selectorLabels" . | nindent 4 }}
{{- end }} 