{{- if .Values.jobs.install.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "orocommerce-simple.fullname" . }}-install
  labels:
    {{- include "orocommerce-simple.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "orocommerce-simple.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "orocommerce-simple.fullname" . }}
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ["sh", "-c", "until nc -z database-orocommerce-simple 5432; do echo 'Waiting for database...'; sleep 2; done"]
      - name: copy-app
        image: "oroinc/orocommerce-application:6.1.0"
        command: ["sh", "-c", "cp -r /var/www/oro/. /var/www/oro-app/ && echo 'Application copied successfully'"]
        volumeMounts:
        - name: oro-app
          mountPath: /var/www/oro-app
      containers:
      - name: install
        image: "oroinc/orocommerce-application:6.1.0"
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["install"]
        envFrom:
        - configMapRef:
            name: {{ include "orocommerce-simple.fullname" . }}-global-config
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: ORO_SAMPLE_DATA
          value: ""
        volumeMounts:
        - name: oro-app
          mountPath: /var/www/oro
        - name: cache
          mountPath: /var/www/oro/var/cache
        - name: public-storage
          mountPath: /var/www/oro/public/media
        - name: private-storage
          mountPath: /var/www/oro/var/data
      volumes:
      - name: oro-app
        persistentVolumeClaim:
          claimName: oro-app-orocommerce-simple
      - name: cache
        persistentVolumeClaim:
          claimName: cache-orocommerce-simple
      - name: public-storage
        persistentVolumeClaim:
          claimName: public-storage-orocommerce-simple
      - name: private-storage
        persistentVolumeClaim:
          claimName: private-storage-orocommerce-simple
{{- end }} 