apiVersion: v2
name: orocommerce-simple
version: 0.1.0
description: Une version simplifiée d'OroCommerce pour le développement local

dependencies:
  - name: webserver
    version: 0.1.0
    repository: file://charts/webserver
    condition: webserver.enabled
  - name: database
    version: 0.1.0
    repository: file://charts/database
    condition: database.enabled
  - name: php-fpm
    version: 0.1.0
    repository: file://charts/php-fpm
    condition: php-fpm.enabled
  - name: websocket
    version: 0.1.0
    repository: file://charts/websocket
    condition: websocket.enabled
  - name: mail
    version: 0.1.0
    repository: file://charts/mail
    condition: mail.enabled 