{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orocommerce.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.backend.labels" . | nindent 4 }}
data:
  parameters.yml: |
    parameters:
        database_host: {{ include "orocommerce.postgresql.hostname" . }}
        database_port: 5432
        database_name: {{ .Values.postgresql.auth.database | default "orocommerce" }}
        database_user: {{ .Values.postgresql.auth.username | default "orocommerce" }}
        database_password: {{ .Values.postgresql.auth.password | default "orocommerce" }}
        
        redis_host: {{ include "orocommerce.redis.hostname" . }}
        redis_port: 6379
        
        elasticsearch_host: {{ include "orocommerce.elasticsearch.hostname" . }}
        elasticsearch_port: 9200
        
        secret: "ThisTokenIsNotSoSecretChangeIt"
        
        mailer_transport: smtp
        mailer_host: localhost
        mailer_port: 587
        mailer_encryption: ~
        mailer_user: ~
        mailer_password: ~
        
        websocket_bind_address: 0.0.0.0
        websocket_bind_port: 8080
        websocket_frontend_host: "*"
        websocket_frontend_port: 80
        websocket_frontend_path: ""
        websocket_backend_host: "*"
        websocket_backend_port: 8080
        websocket_backend_path: ""
        websocket_backend_transport: tcp
        websocket_backend_ssl_context_options: {}
        
        session_handler: snc_redis.session.handler
        
        locale: en
        
        installed: ~
        
        # Configuration pour l'environnement
        env(APP_ENV): {{ .Values.backend.env | default "prod" }}
        env(SYMFONY_ENV): {{ .Values.backend.env | default "prod" }}
{{- end }} 