{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orocommerce.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "orocommerce.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orocommerce.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: orocommerce-app
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          
          # Variables d'environnement simplifiées
          env:
            {{- range .Values.backend.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          
          # Health checks simplifiés
          {{- if .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          {{- end }}
          
          {{- if .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          {{- end }}
          
          # Volumes simplifiés
          volumeMounts:
            - name: media-storage
              mountPath: /var/www/html/public/media
            - name: logs
              mountPath: /var/www/html/var/logs
          
          # Ressources
          {{- if .Values.backend.resources }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- end }}
      
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ include "orocommerce.fullname" . }}-media
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "orocommerce.fullname" . }}-logs
{{- end }} 