{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orocommerce.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.serviceMonitor.enabled }}
    - port: 9253
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "orocommerce.backend.selectorLabels" . | nindent 4 }}
{{- end }} 