{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orocommerce.fullname" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        client_max_body_size 100M;

        # Compression
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/javascript
            application/xml+rss
            application/json;

        # Status page for nginx-exporter
        server {
            listen 8080;
            location /nginx_status {
                stub_status;
                access_log off;
                allow 127.0.0.1;
                deny all;
            }
        }

        server {
            listen 80;
            server_name {{ .Values.global.domain }};
            root /var/www/html/public;
            index index.php;

            # Health check
            location /health {
                return 200 "OK";
                add_header Content-Type text/plain;
                access_log off;
            }

            # PHP files
            location ~ \.php$ {
                fastcgi_pass {{ include "orocommerce.fullname" . }}-backend:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
                fastcgi_read_timeout 300;
            }

            # Static files
            location ~* \.(jpg|jpeg|png|gif|ico|css|js|pdf|txt|tar|gz|woff|woff2|ttf|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
                try_files $uri =404;
            }

            # Default location
            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            # Deny access to sensitive files
            location ~ /\. {
                deny all;
                access_log off;
                log_not_found off;
            }

            location ~ /(var|src|bin|tests|vendor|config)/ {
                deny all;
                access_log off;
                log_not_found off;
            }
        }
    }
{{- end }} 