{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orocommerce.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orocommerce.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.serviceMonitor.enabled }}
    - port: 9113
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "orocommerce.frontend.selectorLabels" . | nindent 4 }}
{{- end }} 