apiVersion: v1
kind: Service
metadata:
  name: ws
  labels:
    app: {{ include "websocket.name" . }}
    {{- include "websocket.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: ws
  selector:
    app: {{ include "websocket.name" . }} 