image:
  repository: docker.io/oroinc/pgsql
  tag: "17.2-alpine"
  pullPolicy: IfNotPresent

env:
  POSTGRES_ROOT_PASSWORD: orocommerce
  POSTGRES_DB: orocommerce
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: orocommerce

service:
  type: ClusterIP
  port: 5432

database:
  replicas: 1
  storage:
    size: 8Gi
    storageClass: ""