image:
  repository: oroinc/runtime
  tag: 6.1-latest
  pullPolicy: IfNotPresent

initContainer:
  image:
    repository: oroinc/orocommerce-application
    tag: 6.1.0
    
  env:
    APP_ENV: "prod"

service:
  type: NodePort
  port: 80
  nodePort: 30080

webserver:
  replicas: 1
  volumes:
    oroApp:
      claimName: "oro-app-orocommerce-simple"
    cache:
      claimName: "cache-orocommerce-simple"
    maintenance:
      claimName: "maintenance-orocommerce-simple"
    publicStorage:
      claimName: "public-storage-orocommerce-simple"
    privateStorage:
      claimName: "private-storage-orocommerce-simple"
